import type { Metadata } from "next";
import "./globals.css";
import HeaderComponent from "@/components/HeaderComponent";
import FooterComponent from "@/components/FooterComponent";
import { MantineProvider } from "@mantine/core";
import BodyBackground from "@/components/BodyBackground";

export const metadata: Metadata = {
  title: "codemasters",
  description: "Generated by create codemasters app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <BodyBackground /> 
        <MantineProvider>
          <HeaderComponent />
          <main>{children}</main>
          <FooterComponent />
        </MantineProvider>
      </body>
    </html>
  );
}
